CREATE DATABASE IF NOT EXISTS kawan_kasir CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kawan_kasir;

CREATE TABLE outlets (id CHAR(36) PRIMARY KEY, name VARCHAR(120) NOT NULL, code VARCHAR(40) NOT NULL UNIQUE, address TEXT, phone VARCHAR(40), email VARCHAR(120), tax_number VARCHAR(80), logo_url VARCHAR(255), is_active BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE permissions (id CHAR(36) PRIMARY KEY, code VARCHAR(100) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL);
CREATE TABLE roles (id CHAR(36) PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL);
CREATE TABLE role_permissions (role_id CHAR(36) NOT NULL, permission_id CHAR(36) NOT NULL, PRIMARY KEY(role_id, permission_id), FOREIGN KEY(role_id) REFERENCES roles(id), FOREIGN KEY(permission_id) REFERENCES permissions(id));
CREATE TABLE users (id CHAR(36) PRIMARY KEY, outlet_id CHAR(36), name VARCHAR(120) NOT NULL, email VARCHAR(120) NOT NULL UNIQUE, username VARCHAR(80) NOT NULL UNIQUE, phone VARCHAR(40), password_hash VARCHAR(255) NOT NULL, role_id CHAR(36) NOT NULL, is_active BOOLEAN DEFAULT TRUE, last_login_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(outlet_id) REFERENCES outlets(id), FOREIGN KEY(role_id) REFERENCES roles(id));
CREATE TABLE categories (id CHAR(36) PRIMARY KEY, outlet_id CHAR(36) NOT NULL, name VARCHAR(120) NOT NULL, description TEXT, is_active BOOLEAN DEFAULT TRUE, FOREIGN KEY(outlet_id) REFERENCES outlets(id));
CREATE TABLE products (id CHAR(36) PRIMARY KEY, outlet_id CHAR(36) NOT NULL, category_id CHAR(36), sku VARCHAR(80) NOT NULL, barcode VARCHAR(100), name VARCHAR(160) NOT NULL, description TEXT, image_url VARCHAR(255), unit VARCHAR(30) DEFAULT 'pcs', purchase_price DECIMAL(18,2) DEFAULT 0, selling_price DECIMAL(18,2) NOT NULL, wholesale_price DECIMAL(18,2), stock INT DEFAULT 0, min_stock INT DEFAULT 0, is_stock_tracked BOOLEAN DEFAULT TRUE, is_active BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(outlet_id) REFERENCES outlets(id), FOREIGN KEY(category_id) REFERENCES categories(id));
CREATE TABLE stock_movements (id CHAR(36) PRIMARY KEY, outlet_id CHAR(36) NOT NULL, product_id CHAR(36) NOT NULL, type VARCHAR(30) NOT NULL, quantity INT NOT NULL, before_stock INT NOT NULL, after_stock INT NOT NULL, reference_type VARCHAR(40), reference_id CHAR(36), note TEXT, created_by CHAR(36), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(outlet_id) REFERENCES outlets(id), FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(created_by) REFERENCES users(id));
CREATE TABLE customers (id CHAR(36) PRIMARY KEY, outlet_id CHAR(36) NOT NULL, name VARCHAR(120) NOT NULL, phone VARCHAR(40), email VARCHAR(120), address TEXT, FOREIGN KEY(outlet_id) REFERENCES outlets(id));
CREATE TABLE shifts (id CHAR(36) PRIMARY KEY, outlet_id CHAR(36) NOT NULL, cashier_id CHAR(36) NOT NULL, opening_cash DECIMAL(18,2) DEFAULT 0, closing_cash DECIMAL(18,2), status VARCHAR(20) NOT NULL, opened_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, closed_at TIMESTAMP NULL, FOREIGN KEY(outlet_id) REFERENCES outlets(id), FOREIGN KEY(cashier_id) REFERENCES users(id));
CREATE TABLE sales (id CHAR(36) PRIMARY KEY, outlet_id CHAR(36) NOT NULL, shift_id CHAR(36), customer_id CHAR(36), invoice_number VARCHAR(80) NOT NULL UNIQUE, cashier_id CHAR(36), subtotal DECIMAL(18,2) NOT NULL, discount DECIMAL(18,2) DEFAULT 0, tax DECIMAL(18,2) DEFAULT 0, total DECIMAL(18,2) NOT NULL, payment_method VARCHAR(30) NOT NULL, paid_amount DECIMAL(18,2) NOT NULL, change_amount DECIMAL(18,2) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE sale_items (id CHAR(36) PRIMARY KEY, sale_id CHAR(36) NOT NULL, product_id CHAR(36) NOT NULL, product_name VARCHAR(160) NOT NULL, quantity INT NOT NULL, price DECIMAL(18,2) NOT NULL, discount DECIMAL(18,2) DEFAULT 0, subtotal DECIMAL(18,2) NOT NULL, FOREIGN KEY(sale_id) REFERENCES sales(id), FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE receipt_settings (id CHAR(36) PRIMARY KEY, outlet_id CHAR(36) NOT NULL, store_name VARCHAR(160) NOT NULL, header_note TEXT, footer_note TEXT, show_logo BOOLEAN DEFAULT TRUE, FOREIGN KEY(outlet_id) REFERENCES outlets(id));
